/** Default IMPACT CREATED showcase cards for seed. */
export const IMPACT_ITEMS = [
  {
    title:
      "Fixed ~97% of fashion thumbnails to 0.75 — CV pipeline for 150k+ listings",
    body: "Drove 8%+ PLP CVR by auto-fixing vendor aspect ratios, framing, and whitespace that broke catalog trust. Two-stage CV pipeline (HF fashion parser + Meta SAM → safe crop → BG stretch) keeps the product mask immutable while hitting a 0.75 container ratio.",
    tags: ["Computer Vision", "Catalog QA", "Aspect Ratio"],
    pdfUrl: "/impact/tv/slikk-aspect-ratio-fix.pdf?v=5",
    logoSrc: "/experience/logos/slikk.png",
    logoAlt: "Slikk",
    logoBg: "#000000",
    logoWide: false,
    themePanel: "#fdeba3",
    themeDot: "#e0b84a",
    themeSplash: "#e8b410",
    themeTag: "#f8f0d0",
    themeAccent: "#f0b800",
    order: 0,
  },
  {
    title:
      "₹700 Cr/day (+0.7%) liquidity lift — Free Float automation 80× faster",
    body: "Cut quarterly FFF work from 20 days × 3 FTEs to 1 day × 1 FTE with an Excel–SQL rule engine, eliminating 1–5% free-float errors on 300 of 4,800+ stocks. Also automated branded sales PDFs across 101 indices — 90% less prep, 30+ hrs/month saved, 20% faster client TAT.",
    tags: ["Index Analytics", "Automation", "Free Float"],
    pdfUrl: "/impact/tv/bse-intern-work.pdf?v=4",
    logoSrc: "/experience/logos/bse.png",
    logoAlt: "BSE",
    logoBg: "#ffffff",
    logoWide: true,
    themePanel: "#ddeff5",
    themeDot: "#5aa8c8",
    themeSplash: "#4fb0d8",
    themeTag: "#eef6fa",
    themeAccent: "#4aa3d4",
    order: 1,
  },
  {
    title:
      "Unified Zoho–Excel–calls into one client dashboard — +40% feature adoption",
    body: "Shipped EMB’s client portal for projects, commercials, and staff augmentation so clients track delivery, money, and resources in one place. API integrations collapsed fragmented journeys across Zoho, Excel, and calls, lifting adoption 40%.",
    tags: ["Client Portal", "Dashboard UX", "Project Ops"],
    pdfUrl: "/impact/tv/emb-client-dashboard.pdf?v=4",
    logoSrc: "/experience/logos/emb.png",
    logoAlt: "EMB Global",
    logoBg: "#ffffff",
    logoWide: false,
    themePanel: "#ecf5d4",
    themeDot: "#7aab4a",
    themeSplash: "#74c44a",
    themeTag: "#eef6e0",
    themeAccent: "#6fbf48",
    order: 2,
  },
  {
    title:
      "Boosted OTA & organic bookings 25% — 20+ flows + OTA Manager SaaS",
    body: "Designed 20+ high-fidelity booking flows to deepen brand story and lift OTA/organic revenue, and integrated OTA Manager SaaS to save 50+ hrs/month. Built a no-code listing hub and guest check-in portal that cut approval time ~70%.",
    tags: ["Homestay", "OTA", "Product Design"],
    pdfUrl: "/impact/aarya-stays-website-checkin.pdf",
    logoSrc: "/experience/logos/aarya.png",
    logoAlt: "Aarya Stays",
    logoBg: "#ffffff",
    logoWide: false,
    themePanel: "#f5d4e4",
    themeDot: "#d478a0",
    themeSplash: "#e878a8",
    themeTag: "#f8e8f0",
    themeAccent: "#e878a8",
    order: 3,
  },
] as const;
